export default function SEOSection() {
  return (
    <section id="about" className="section-padding bg-gray-950">
      <div className="container">
        <div className="max-w-4xl mx-auto space-y-16">
          
          {/* Main About Section */}
          <div className="text-center">
            <h2 className="text-4xl md:text-5xl font-bold mb-8 gradient-text">
              The Ultimate AI Earth Zoom Out Experience
            </h2>
            <p className="text-xl text-gray-300 leading-relaxed">
              Transform any image into a spectacular earth zoom out video with cutting-edge artificial intelligence. 
              Our revolutionary technology creates seamless transitions from your personal photos to the cosmic perspective of Earth.
            </p>
          </div>

          {/* What is Earth Zoom Out */}
          <div className="card">
            <h2 className="text-3xl font-bold mb-6 text-white">
              What is Earth Zoom Out Video Generation?
            </h2>
            
            <div className="space-y-6 text-gray-300 leading-relaxed">
              <p>
                An earth zoom out video is a cinematic technique that begins with a close-up view of a specific location 
                and gradually zooms out to reveal the entire planet Earth from space. This dramatic perspective shift 
                creates an awe-inspiring visual journey that showcases the scale and beauty of our world.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                The Magic Behind AI Earth Zoom Out Technology
              </h3>
              
              <p>
                Our AI earth zoom out generator uses advanced machine learning algorithms to analyze your uploaded image 
                and create a seamless transition sequence. The technology intelligently identifies the geographic context 
                of your photo and generates intermediate frames that smoothly transition from your original image to a 
                satellite view, aerial perspective, and finally to the complete Earth zoom out effect.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Professional Quality Earth Zoom Out Videos
              </h3>
              
              <p>
                Every earth zoom out video generated by our platform maintains professional broadcast quality. The AI 
                ensures smooth camera movements, realistic atmospheric effects, and accurate geographic transitions. 
                Whether you start with a street-level photo, landscape image, or aerial shot, the earth zoom out 
                sequence will be scientifically accurate and visually stunning.
              </p>
            </div>
          </div>

          {/* How It Works */}
          <div className="card">
            <h2 className="text-3xl font-bold mb-6 text-white">
              How Our Earth Zoom Out Generator Works
            </h2>
            
            <div className="space-y-6 text-gray-300 leading-relaxed">
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Step-by-Step Earth Zoom Out Creation Process
              </h3>
              
              <p>
                Creating your earth zoom out video is incredibly simple. First, upload any image - whether it's a 
                vacation photo, landscape shot, or urban scene. Our AI earth zoom out technology analyzes the image 
                to understand the geographic location and visual context. Then, select your preferred video duration 
                (5 or 10 seconds) to determine how long your earth zoom out sequence will be.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Advanced AI Processing for Earth Zoom Out Effects
              </h3>
              
              <p>
                Once you click generate, our sophisticated AI begins creating your earth zoom out video. The system 
                generates multiple intermediate frames, each representing a different altitude and perspective. The 
                earth zoom out effect progresses through distinct phases: ground level detail, elevated perspective, 
                aerial view, atmospheric layer transition, orbital perspective, and finally the complete Earth zoom out 
                showing our planet in space.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Seamless Earth Zoom Out Transitions
              </h3>
              
              <p>
                The most challenging aspect of creating earth zoom out videos is maintaining visual continuity throughout 
                the dramatic scale changes. Our AI earth zoom out generator excels at this, using advanced interpolation 
                techniques to ensure each frame flows naturally into the next. The result is a smooth, professional 
                earth zoom out video that rivals those created by major film studios.
              </p>
            </div>
          </div>

          {/* Applications and Uses */}
          <div className="card">
            <h2 className="text-3xl font-bold mb-6 text-white">
              Creative Applications for Earth Zoom Out Videos
            </h2>
            
            <div className="space-y-6 text-gray-300 leading-relaxed">
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Social Media and Content Creation
              </h3>
              
              <p>
                Earth zoom out videos are incredibly popular on social media platforms. These dramatic sequences 
                capture viewers' attention and create memorable content that stands out in crowded feeds. Content 
                creators use earth zoom out effects to add cinematic flair to their posts, making ordinary photos 
                extraordinary through the power of perspective.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Educational and Documentary Uses
              </h3>
              
              <p>
                Educators and documentary filmmakers frequently employ earth zoom out techniques to illustrate scale, 
                geography, and our planet's place in the universe. An earth zoom out video can effectively demonstrate 
                concepts ranging from local geography to global perspective, making complex spatial relationships 
                easily understandable for audiences of all ages.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Marketing and Brand Storytelling
              </h3>
              
              <p>
                Businesses leverage earth zoom out videos for impactful marketing campaigns. The dramatic perspective 
                shift inherent in earth zoom out sequences creates emotional resonance and can effectively communicate 
                messages about global reach, environmental consciousness, or the interconnected nature of our world. 
                Many brands use earth zoom out effects to conclude advertisements with powerful visual statements.
              </p>
            </div>
          </div>

          {/* Technical Excellence */}
          <div className="card">
            <h2 className="text-3xl font-bold mb-6 text-white">
              Technical Excellence in Earth Zoom Out Generation
            </h2>
            
            <div className="space-y-6 text-gray-300 leading-relaxed">
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                High-Definition Earth Zoom Out Quality
              </h3>
              
              <p>
                Our earth zoom out generator produces videos in high definition, ensuring every detail remains crisp 
                throughout the zoom sequence. From the initial close-up of your uploaded image to the final earth zoom out 
                revealing our planet against the cosmos, every frame maintains professional broadcast quality standards.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Realistic Earth Zoom Out Physics
              </h3>
              
              <p>
                The earth zoom out videos generated by our AI follow realistic physics and atmospheric effects. As the 
                perspective rises through different altitudes, the AI accurately simulates atmospheric haze, curvature 
                effects, and the transition from daylight to the darkness of space. This attention to detail makes each 
                earth zoom out sequence scientifically plausible and visually compelling.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Customizable Earth Zoom Out Duration
              </h3>
              
              <p>
                Understanding that different projects require different pacing, our earth zoom out generator offers 
                flexible duration options. Whether you need a quick 5-second earth zoom out for social media or a 
                more contemplative 10-second sequence for documentary work, our AI adapts the transition timing to 
                create the most effective earth zoom out experience for your specific needs.
              </p>
            </div>
          </div>

          {/* Future of Earth Zoom Out */}
          <div className="card">
            <h2 className="text-3xl font-bold mb-6 text-white">
              The Future of AI Earth Zoom Out Technology
            </h2>
            
            <div className="space-y-6 text-gray-300 leading-relaxed">
              <p>
                As artificial intelligence continues to evolve, earth zoom out video generation will become even more 
                sophisticated and accessible. We're continuously improving our AI earth zoom out algorithms to provide 
                faster processing, higher quality output, and more customization options. The future of earth zoom out 
                creation lies in making this powerful cinematic technique available to everyone, regardless of their 
                technical expertise or budget.
              </p>
              
              <h3 className="text-2xl font-semibold text-white mt-8 mb-4">
                Expanding Earth Zoom Out Possibilities
              </h3>
              
              <p>
                Future developments in earth zoom out technology will include enhanced customization options, such as 
                different planetary perspectives, historical earth imagery integration, and even zoom out sequences 
                extending beyond Earth to show our solar system. The possibilities for creative earth zoom out 
                applications are limitless as AI technology continues to advance.
              </p>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}